### ISSUE TITLE
Insider build 0.12.4 breaks the plugin

### ISSUE THREAD

**Issue by danraymond** [alexandru-dinu/obsidian-sortable#13]
Tried this with the new insider build 0.12.4 and can't get the plugin to load at all.

**Comment by alexandru-dinu** [comment]
Hello @danraymond,

Thanks for reporting.
I tested the plugin with 0.12.4 and it seems to work fine.
https://user-images.githubusercontent.com/14110183/119617014-02bfb280-be0a-11eb-84ec-1f4ab0ec7705.mov

If you open developer console, you should see the following:
```
loading sortable plugin
```

Can you please provide additional info? What other plugins are you using?

**Comment by alexandru-dinu** [comment]
Closing this as no further information was provided.
If a problem occurs, please open a new issue with specific problem details.
