### ISSUE TITLE
Sorting by Date-and-Time columns does not change the order - only reverts to original order

### ISSUE THREAD

**Issue by claremacrae** [alexandru-dinu/obsidian-sortable#17]
**Describe the bug**

Columns with Date and Time only sort to the original order. Requests for Ascending or Descending order appear to be ignored.

**To Reproduce**

1. Obsidian v0.12.15
2. Sortable 0.2.0 installed
3. Grab this table:

```text
| Order | File          | Dates            | Dir         |
| ----- | ------------- | ---------------- | ----------- |
| 1     | Table Sorting | 2021-09-29-22:38 | Tables      |
| 2     | Unwanted Tags | 2021-09-24-20:28 | Tag Testing |
| 3     | Obsidian      | 2021-09-25-20:20 | Tag Testing |
| 4     | Tag File 6    | 2021-09-24-20:11 | Tag Testing |
| 5     | Tag File 5    | 2021-09-22-20:11 | Tag Testing |
| 6     | Tag File 4    | 2021-09-24-19:58 | Tag Testing |
```

4. Sort each of Order, File and Dir columns by each of Ascending, Descending, Original to confirm that plugin is working as expected.
5. Sort Dates column by each of Ascending, Descending, Original - it only ever reverts to original order, whilst cycling through all the 3 icons. In other words, sorting by Date-and-Time columns seems broken,

**Expected behavior**

Sorting on Dates and Times works for ascending and descending orders

**Video Demo**

**Please Note: When I recorded this, I only had Sortable enabled. However, the behaviour is the same when Advanced Tables 0.13.0 is installed and enabled**

https://user-images.githubusercontent.com/4840096/135479491-4e92e8b7-92a8-4ecd-a7cf-17d3910eafda.mov

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.7
 - Obsidian Version: v0.12.15
 - Sortable 0.2.0 installed

**Additional context**

Can't think of anything. Just wanted to say "thanks" for a really helpful plugin!

**Comment by claremacrae** [comment]
Thanks for the swift reply. It's certainly not urgent to fix.

I must admit that bit of the README hadn't sunk in, but I might have assumed that there were numerical values. I take your point, though, that they are not.

In the meantime, might it be feasible to fall-back on treating other data types as strings, and sorting their unmodified string representation? This would give the desired value in this, and I suspect many other cases.

**Comment by alexandru-dinu** [comment]
I believe that's a fair point. There are certainly lots of edge cases (e.g. time zones, currencies etc.), but it's a good step forward.

For the meantime, I'd let let the user specify their preferred datetime format string in the settings. 
Maybe even annotate table's column with the data type?

**Comment by claremacrae** [comment]
Thanks. How would I do that annotation please? (My tables are generated by dataview)

**Comment by alexandru-dinu** [comment]
Right, it may be trickier in this case -- there's #6 on the roadmap as well.

**Comment by claremacrae** [comment]
Oh sorry, I thought you were mentioning an existing feature, maybe I misunderstand. Not to worry.

Thanks for the replies anyway, and thanks again for the useful plugin.

**Comment by alexandru-dinu** [comment]
Yes, sorry for the misunderstanding, column annotation was just an idea.

**Comment by claremacrae** [comment]
Yes, down the line it would be nice for the sorting to “just work” but I totally realise the nature of maintaining open-source projects and not everything can be done - I’ve been there myself on C++ projects…

For now, this is already really useful.

**Comment by alexandru-dinu** [comment]
> down the line it would be nice for the sorting to “just work”

I fully agree with this -- minimal tinkering on user's part!
I will research more into how Wikipedia achieves this, since it's the main source of inspiration for this plugin.

I appreciate the feedback and I am glad that people find this useful!

**Comment by alexandru-dinu** [comment]
Tracked in #18.

**Comment by alexandru-dinu** [comment]
To summarize: 

At the time of writing, Sortable can only sort numeric and string data types. In your example, **all** the values from the `Dates` column get parsed as numbers, i.e. `2021`, so the order  does not change.

Supporting other data types is tracked in #18.

For the immediate future, I will allow the user to specify a date-time format string in plugin's settings and use that to try to parse date-time values.

Again, thank you for reporting. Closing this as the main issue for this problem will be #18.
