### ISSUE TITLE
Submitting Sortable to Community Plugins

### ISSUE THREAD

**Issue by kepano** [alexandru-dinu/obsidian-sortable#19]
This is a fantastic plugin which I have been using for months without issue. Do you have a plan to adding it to the Community Plugins so it is easier for people to download?

**Comment by kepano** [comment]
For context, in an upcoming version of Minimal theme, I've created some functionality that relies on Sortable to help people turn Dataview tables into cards. I would love to recommend Sortable to users, but it would be easier if it was in the Community Plugins. Thanks!

![2022-01-03 14 06 56](https://user-images.githubusercontent.com/10565871/147986729-039e655a-e62d-4f27-b36b-7e8ec090b81f.gif)

**Comment by alexandru-dinu** [comment]
Hi,

I took some time off from Obsidian these last few months, but I am planning on fixing #17 first, then submitting it as a community plugin.

Sorry for any inconvenience. I am glad that people find the plugin useful.

-- Alex

**Comment by alexandru-dinu** [comment]
PR here: https://github.com/obsidianmd/obsidian-releases/pull/727

**Comment by alexandru-dinu** [comment]
PR merged, the plugin is now available in "Community Plugins".

![image](https://user-images.githubusercontent.com/14110183/150703178-6443a12a-12ca-4620-8cef-d110bd6c8da4.png)
