### ISSUE TITLE
Exclude dataview calendar

### ISSUE THREAD

**Issue by mnvwvnm** [alexandru-dinu/obsidian-sortable#20]
Hi.
Dataview has a new query type: [calendar](https://github.com/blacksmithgu/obsidian-dataview/releases/tag/0.4.22)
However, this calendar is render as a table and the sort "triangles" elements are render too.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/22862501/149596275-0a1c9f50-0448-4502-ba82-4fb1737004bb.png">

But these are absolutely unnecessary in calendar format.
Is there any way to exclude these specific tables from the sortable plugin?

**Comment by mnvwvnm** [comment]
Nevermind. From one moment to another it's gone...
<img width="736" alt="image" src="https://user-images.githubusercontent.com/22862501/149602116-802a9868-d1eb-4a96-a7c0-0985a510063a.png">

**Comment by alexandru-dinu** [comment]
Hi,

Can you please provide a text example that renders as a calendar, so that I can test?

Thank you!

**Comment by mnvwvnm** [comment]
Hi.
Thank you for answer. For now the issue is gone.
But sure, you can test with:

````
```dataview
CALENDAR file.mday
FROM "your-folder"
```
````

Thank you.

**Comment by alexandru-dinu** [comment]
Hi,

Thanks for reporting, I will look into it.
I will close the issue for now, but if there is any other problem feel free to reopen it!

**Comment by mnvwvnm** [comment]
ok. thank you
