### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by scriptor-dga** [alexandru-dinu/obsidian-sortable#21]
I tried to install Sortable both by downloading the repo in the plugin folder and also with the BRAT plugin. In the first case, when I try to toggle on Sortable in the community plugins settings, it says "Failed to load Sortable" and it stays off. And if I use BRAT, I can successfully toggle Sortable on, but I can't find it in the list of activated plugins on the left. Nor can I find it from the command palette.

**Comment by alexandru-dinu** [comment]
Hello,

Cloning the repo will not install the plugin, as you essentially need the `main.js` file which is not tracked by git.

You have to:
- download `main.js`, `manifest.json`, `styles.css` from the latest [release](https://github.com/alexandru-dinu/obsidian-sortable/releases)
- move them to `vault/.obsidian/plugins/obsidian-sortable/`
- enable "Sortable" from the Obsidian "Community plugins" settings

Please try again and let me know how it goes.

I am not familiar with the BRAT plugin -- the installation should not require additional stuff.
Furthermore, there is an [open pull request](https://github.com/obsidianmd/obsidian-releases/pull/727) to have Sortable listed in the community plugins. 
When approved, this is facilitate the installation process.

Thanks!

**Comment by alexandru-dinu** [comment]
Yes, I mentioned above that there's an open pull request that, when accepted, will officially list the plugin in the "community plugins" section. This is the way Obsidian manages their plugin system.

As of right now, the plugin can only be installed manually.
