### ISSUE TITLE
Feature request: Live Preview support

### ISSUE THREAD

**Issue by kabo1234** [alexandru-dinu/obsidian-sortable#22]
Hi,

this is a great plugin! And now that Dataview tables work in live preview, it would be great if Sortable would work in live preview as well! 

At the moment I have to switch to reading mode to sort, and when I return to live preview the order returns to Dataview default…

is this something that is possible?

**Comment by alexandru-dinu** [comment]
Hello,

Thanks for bringing this up!
Unfortunately, I am not familiar with nor using live preview, but I will look into this.

-- Alex

**Comment by alexandru-dinu** [comment]
Hello,

Thanks for bringing this up!

First, it appears that Sortable behaves fine in live preview mode (without Dataview).
It provides a _view_ of the sorted table, so in editing mode you still get the raw (unsorted) data.

To further investigate this, can you please provide a description of a reproducible workflow, using Dataview, that I can test?

-- Alex

**Comment by kabo1234** [comment]
Hi Alex,

thanks for the quick reply! Here is a screen recording that shows the issue (it's the same for table view as for cards view):

https://capture.dropbox.com/CE6hwR64W9I148B3?src=ss

you can see that when I go to preview mode ti works fine, but in LP sortable doesn't react to my clicking. 

I'm using the minimal theme, in case that might be the interfering issue? I'll try it in a test vault as well.

Thanks,
KB

**Comment by alexandru-dinu** [comment]
Hi KB,

Thanks for providing additional info. Will look into this and try to provide a fix.

-- Alex

**Comment by alexandru-dinu** [comment]
Hi, 

I tried to replicate your example.
I have 3 files `{foo,bar,baz}.md`, each containing just frontmatter data
```yaml
# foo
---
tags: dv-test
idx: 10
cover: assets/foo.png
---

# bar
---
tags: dv-test
idx: 1
cover: assets/bar.png
---

# baz
---
tags: dv-test
idx: 4
cover: assets/baz.png
---
```

Then I constructed the following Dataview query:
```
TABLE WITHOUT ID
("![](" + cover + ")") as Cover,
file.link as Title,
idx as Index
FROM #dv-test
```
but it does not render the images:
![image](https://user-images.githubusercontent.com/14110183/154672144-9227ad40-02b8-414a-b60a-87f62e10518a.png)

Also, I enabled:
- Live preview
- Minimal theme with "Image grids" setting

Thus, I am assuming there is something else going on. 
I notice you have a `cssclasses` keyword -- what is its purpose?

**Comment by kabo1234** [comment]
Hi, thanks for looking into this!

that's great that Sortable works in Live Preview! 

I should have been more clear... 

- ```Sort number(meta(sem-week).display) asc``` I have taken out of the query and just parked there as text for future reference - it does nothing
- in Minimal, the cssclass is actually 'cards' not image grid
- I tried the same query in a different vault with no snippets and just the default theme, and using table view (just normal), and Sortable still only works in Reading mode, not Live Preview. There is no indicator to sort the table, only when I swap to Reading Mode (no change if I take out the cover images). I can't sort by title or week unless I go to Reading Mode...
- I remember reading something about the difference between using local images and online images, but unfortunately I can't remember what the issue was there...for what it's worth, the YAML in the originating file looks like this:

```
---
cover: https://m.media-amazon.com/images/M/MV5BNjQ1NTQyYjktZDc5My00NDA1LWI1NmItY2ViNjQ0NDk4NmRjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg
---
```

'Title' is derived from 'file.link' and 'Week' is an inline dataview field, eg 
```week:: [[2022-CourseID-Week 5|5]] ```

I tried using a plain text field, such as 'year:: 1992' to check whether it is the links that are the problem, but that makes no difference, still can't sort until go to Reading mode. 

```
dataview
table WITHOUT ID file.link as Title, year as Year, sem-week as Week
from "02 Research/films and tv series" 
```

Could you show me a sample where the sorting works in Live Preview, and maybe I can see what's different to my setup?

**Comment by alexandru-dinu** [comment]
Hi, 

Sorry for the delay and thank you for the info!

---

> Sortable still only works in Reading mode, not Live Preview.

First, there seems to be a confusion here between "reading mode" / "live preview" etc.

Sortable works **only** in the reading (i.e. **non-editing**) mode. This is mentioned in the readme: "No altering of the markdown source code. Sorting is done solely in preview mode by rearranging rows."

In my comment above, I thought that there's a bug that makes Sortable unusuable when editing tables in "live preview" mode, then switching to "reading mode".

> Could you show me a sample where the sorting works in Live Preview, and maybe I can see what's different to my setup?

I mistook "live preview" for "reading mode", I apologize.

> Sortable still only works in Reading mode, not Live Preview. There is no indicator to sort the table, only when I swap to Reading Mode (no change if I take out the cover images). I can't sort by title or week unless I go to Reading Mode...

Yes, that is expected and it is the default behaviour. You cannot use Sortable when you're in an editing mode (either classical or live preview).

---

For the moment, one workaround may be to keep two open panes for a given file: one in editing mode (live preview), the other in reading mode -- you can interact with tables in reading mode and do the editing using live preview.

Hopefully this clarifies the issue. Do let me know if you have any questions!

-- Alex

**Comment by alexandru-dinu** [comment]
Hi,

It doesn't /shouldn't work in Live Preview.
Can you please verify again?

Thanks
-- Alex

**Comment by nousernameavailableanymore** [comment]
> Hi, It doesn't /shouldn't work in Live Preview. Can you please verify again? Thanks -- Alex

I can confirm that it does not work in Live Preview.
This was meant as "I would also appreciate to see this work in LP" :)

**Comment by alexandru-dinu** [comment]
Thank you.
At the moment  I am not sure what needs to be changed in order to support this, but I'll try to make it work.

**Comment by alexandru-dinu** [comment]
Thank you.

I am not currently sure what the required changes are -- in order to support this -- but I'll have a got at it.

**Comment by alexandru-dinu** [comment]
Introduced in https://github.com/alexandru-dinu/obsidian-sortable/releases/tag/0.2.3.
