### ISSUE TITLE
FR: Use `Intl.Collator` to sort "naturally" instead of showing 1, 10, 2, 3, etc.

### ISSUE THREAD

**Issue by ManasMadrecha** [alexandru-dinu/obsidian-sortable#24]
Hi, this is a very useful plugin. But currently, it sorts in an non-intuitive way (i.e., 10 comes before 2). It would be better if the plugin sorted like the File Explorer does in Windows or Obsidian or VS Code.

**Comment by alexandru-dinu** [comment]
Hi,

Thank you for reporting this issue.

Currently, the plugin only sorts numeric and string data types (without assuming any other info).
I will add natural file sorting to the roadmap.

-- Alex

**Comment by ManasMadrecha** [comment]
Sure. 

But, the thing with using `Intl.Collator` is that **you won't need to specify whether the content is text or number**; it can sort naturally on its own. 

```javascript
const collator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});

<arrayOfObjects>.sort((a, b) => collator.compare(a.something, b.something))
```

Here, you don't need to check whether the contents of the table cell were text, path, or number. 

So, instead of roadmap, could it be kindly implemented immediately?

**Comment by alexandru-dinu** [comment]
Hi,

Thank your for your suggestions.
If you have a complete solution in mind, a pull request is more than
welcome.

Otherwise, I will get back to this as soon as I got the time. Thank you!

-- Alex

**Comment by alexandru-dinu** [comment]
> Here, you don't need to check whether the contents of the table cell were text, path, or number.

It appears that the data type still matters:
```js
let xs = [1, 2, -5, 3, 1e100, -1e100];
const c = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
console.log(xs.sort(c.compare))
// > Array [-1e+100, -5, 1, 1e+100, 2, 3]
```

**Comment by alexandru-dinu** [comment]
Done in https://github.com/alexandru-dinu/obsidian-sortable/pull/25 -- thank you for your suggestion!
