### ISSUE TITLE
Can't sort according to dates

### ISSUE THREAD

**Issue by SakethKanchi** [alexandru-dinu/obsidian-sortable#27]
![Obsidian_R2AI1RpyEC](https://user-images.githubusercontent.com/70198692/174008969-20b09649-20b3-4f2d-9f8f-91e368c564f1.gif)

## Here is a template
```

|  Col1         |  Col2            |  Col3              |  Col4              |  Col5              |  Dates      |
|:--------------|:-----------------|:-------------------|:-------------------|:-------------------|:------------|
| Testing Title | Testing Column 2 | Testing Column 3   | Testing Column 3   | Testing Column 5   |  2022-04-17 |
| Testing Title | Testing Column 2 | Testing Column 3   | Testing Column 3   | Testing Column 5   |  2022-06-05 |
| Testing Title | Testing Column 2 |  Testing Column 3  |  Testing Column 4  |  Testing Column 5  |  2022-03-10 |  
```

**Comment by colintedford** [comment]
I found that if you delete the dashes and just run the numbers all together (like `20220417`), they will sort. Obviously that’s hard to read, but it’s a clue.

I tried replacing the dashes with spaces (`2022 04 17`), and the column wouldn’t sort.

I found a workaround: put a letter at the start, like `d 2022-04-17`. Actually, even punctuation works (I only tested a period): `. 2022-04-17`.

**Comment by SakethKanchi** [comment]
I'll use the workaround, thank you. I'll try to experiment with it.

**Comment by alexandru-dinu** [comment]
Hi,

This is a known limitation at the moment. Will try to address that as soon as possible.
Sorry for the inconvenience.
