### ISSUE TITLE
Live Preview support for native (non-dataview) tables

### ISSUE THREAD

**Issue by HyperEpsilon** [alexandru-dinu/obsidian-sortable#29]
I saw that #22 has been implemented, but I'm wondering if the same would be possible for native tables created with `|` to be sorted in Live Preview?

I know it might be tricky as clicking anywhere on the table currently opens it for editing.

**Comment by alexandru-dinu** [comment]
Hi,

Please see https://github.com/alexandru-dinu/obsidian-sortable/discussions/23#discussioncomment-2457695

**Comment by HyperEpsilon** [comment]
Ah thanks, I didn't see it in the comments. I'll close this issue then.
