### ISSUE TITLE
Sorting by date is flawed

### ISSUE THREAD

**Issue by ThurMeijer** [alexandru-dinu/obsidian-sortable#33]
When sorting by date, Sortable uses the string instead of the iso-date. For example:

I have my release dates logged as iso-date: `ReleaseDate:: YYYY-MM-DD`, but my standard date-view is `DD-MM-YYYY`.

When I use Sortable it sorts by `DD-MM-YYYY`, which means 31-05-2022 is later than 15-10-2022.

Is is possible to recognize dates and use iso-dates?

**Comment by alexandru-dinu** [comment]
Sorry for the extremely late reply. Implemented an ad-hoc solution until I think of something smarter. Hope it works!
