### ISSUE TITLE
Does not work on a secondary window.

### ISSUE THREAD

**Issue by ironhak** [alexandru-dinu/obsidian-sortable#34]
Plugin does not work if the tbale is on a note opened in a window that is not the main obsidian window.

**Comment by alexandru-dinu** [comment]
Hello,

Can you please provide some more context to the problem?
What is the meaning of a "secondary window"? How does it differ from the "main window"?

Furthermore, what "does not work" mean here, specifically? Does not sort at all, sorting is wrong, no cycling through asc / desc.. etc?

**Comment by alexandru-dinu** [comment]
Fixed in [0.3.1](https://github.com/alexandru-dinu/obsidian-sortable/releases/tag/0.3.1).
